version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-gp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: failing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src:/var/lib/postgresql/data2
    restart: always
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-gp
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  postgres_data:
    driver: local

networks:
  postgres-network:
    driver: bridge
