version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-gp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: failing
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src:/var/lib/postgresql/data2
    restart: always

volumes:
  postgres_data:
    driver: local
